// js/components/report-labels.js
// خريطة اسم الحقل بالكود -> تسمية عربية، تُستخدم بتوليد تقرير الـ PDF
// كل مفتاح هنا يقابل اسم حقل حقيقي بأحد صفحات الأقسام (data-field أو id)

export const FIELD_LABELS = {
  "mainEntity": "الجهة الرئيسة",
  "entityType": "الجهة التي ترفع التقرير",
  "departmentName": "اسم الجهة (القسم)",
  "otherDepartmentName": "اسم القسم (أخرى)",
  "officeName": "اسم المكتب",
  "unitName": "اسم الوحدة",
  "month": "الشهر",
  "semester": "الفصل",
  "hijriYear": "العام الهجري",
  "startDate": "تاريخ البداية",
  "endDate": "تاريخ النهاية",
  "preparerName": "الاسم",
  "preparerTitle": "المسمى الوظيفي",
  "directManager": "اسم الرئيسة المباشرة",
  "name": "اسم المؤشر",
  "classification": "تصنيف المؤشر",
  "direction": "اتجاه المؤشر",
  "nature": "طبيعة المؤشر",
  "frequency": "دورية القياس",
  "baseline": "خط الأساس",
  "target": "المستهدف",
  "actual": "المتحقق",
  "unit": "وحدة القياس",
  "previousPeriod": "الفترة السابقة",
  "dataSource": "مصدر البيانات",
  "deviationAmount": "مقدار الانحراف",
  "deviationReason": "سبب الانحراف",
  "reasonType": "هل السبب داخلي أم خارجي؟",
  "correctiveAction": "الإجراء التصحيحي",
  "responsible": "المسؤولة عن الإجراء",
  "closingDate": "موعد إغلاق المعالجة",
  "supportNeeded": "الدعم المطلوب",
  "workType": "نوع العمل",
  "otherWorkType": "حددي نوع العمل",
  "goal": "الهدف منه",
  "targetGroup": "الفئة المستهدفة",
  "targetCount": "العدد المستهدف",
  "actualBeneficiaries": "عدد المستفيدات الفعلي",
  "location": "مقر التنفيذ",
  "mode": "طريقة التنفيذ",
  "executingEntity": "الجهة المنفذة",
  "partners": "الجهات المشاركة",
  "executionStatus": "حالة التنفيذ",
  "attendeesCount": "عدد الحاضرات",
  "continuationRate": "نسبة الاستمرار %",
  "approvedCost": "التكلفة المعتمدة",
  "actualCost": "التكلفة الفعلية",
  "keyResult": "أبرز نتيجة (جملة واحدة تصف النتيجة، وليس النشاط فقط)",
  "toolType": "نوع الأداة",
  "otherToolType": "حددي نوع الأداة",
  "purpose": "الهدف من استخدامها",
  "relatedEntity": "الجهة أو البرنامج المرتبط بها",
  "appliedGroup": "الفئة التي طبقت عليها",
  "populationSize": "حجم المجتمع",
  "sampleSize": "حجم العينة",
  "respondentsCount": "عدد المستجيبات",
  "applicationDate": "تاريخ التطبيق",
  "toolLink": "رابط نسخة الأداة",
  "resultsLink": "رابط نتائجها",
  "quality": "جودة نتائج الأداة",
  "domain": "مجال نقطة القوة",
  "otherDomain": "حددي المجال",
  "description": "وصف نقطة القوة",
  "evidence": "الدليل عليها",
  "impact": "أثرها",
  "maintainHow": "كيف يمكن المحافظة عليها؟",
  "level": "مستوى الصعوبة",
  "scope": "نطاق الصعوبة",
  "rootCause": "سببها الجذري",
  "recurred": "هل تكررت سابقًا؟",
  "stillOngoing": "هل ما زالت قائمة؟",
  "actionTaken": "الإجراء الذي اتخذته الوحدة",
  "actionResult": "نتيجة الإجراء",
  "proposedEntity": "الجهة المقترحة للمعالجة",
  "timeNeeded": "المدة اللازمة للمعالجة",
  "area": "المجال الذي يمكن تحسينه",
  "currentState": "الوضع الحالي",
  "desiredState": "الوضع المرغوب",
  "gap": "الفجوة بينهما",
  "improvementAction": "الإجراء التحسيني المقترح",
  "expectedImpact": "الأثر المتوقع",
  "ease": "سهولة التنفيذ",
  "priority": "الأولوية",
  "targetDate": "تاريخ التنفيذ المستهدف",
  "successIndicator": "مؤشر قياس نجاح التحسين",
  "type": "نوع المبادرة",
  "status": "حالة المبادرة",
  "responsibleEntity": "الجهة المسؤولة",
  "preliminaryResults": "نتائجها الأولية",
  "transferable": "هل هي قابلة للتعميم على وحدات أخرى؟",
  "title": "عنوان القصة",
  "beneficiaryDesc": "وصف عام للمستفيدة (دون اسم صريح)",
  "beforeState": "الوضع قبل التدخل",
  "intervention": "التدخل الذي تم",
  "afterState": "الوضع بعد التدخل (الأثر)",
  "publishable": "هل يمكن نشرها إعلاميًا؟",
  "text": "نص التوصية",
  "basedOn": "مبنية على أي نتيجة (رقم مؤشر / تحليل)",
  "timeframe": "المدة الزمنية المقترحة",
  "resourcesNeeded": "الموارد المطلوبة",
  "relatedSection": "القسم المرتبط به",
  "confidentiality": "درجة السرية",
  "notes": "ملاحظات",
  "periodType": "الفترة التي يغطيها التقرير",
  "strategicGoal": "الهدف المرتبط بالخطة الاستراتيجية",
  "operationalGoals": "الأهداف التشغيلية للوحدة",
  "achievementLevel": "مستوى تحقق الهدف",
  "achievementRatio": "نسبة تحقق الهدف %",
  "achievementExplanation": "تفسير مستوى التحقق",
  "evidenceOther": "دليل تحقق الهدف (أخرى)",
  "generalSummary": "الخلاصة التحليلية",
  "topPositiveResult": "أبرز نتيجة إيجابية",
  "topImprovementResult": "أبرز نتيجة تحتاج إلى تحسين",
  "comparisonSubject": "موضوع المقارنة",
  "comparisonResult": "نتيجة المقارنة",
  "comparisonJudgement": "الحكم على المقارنة",
  "changeReason": "سبب التغير",
  "items": "الأعمال الرئيسة للفترة القادمة",
  "fileName": "اسم الملف",
  "externalLink": "رابط الملف"
};

export function fieldLabel(key) {
  return FIELD_LABELS[key] || key;
}
